# Generated by Django 5.2.8 on 2026-01-01 20:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creditor',
            fields=[
                ('creditor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='نام طلبکار')),
                ('creditor_type', models.CharField(choices=[('PERSON', 'فرد'), ('COMPANY', 'شرکت'), ('SHOP', 'مغازه')], max_length=10, verbose_name='نوع طلبکار')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('address', models.CharField(max_length=255, verbose_name='آدرس')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPurchase',
            fields=[
                ('cp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ خرید')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='مجموع خرید')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('birth_date', models.DateField(verbose_name='تاریخ تولد')),
                ('gender', models.CharField(choices=[('M', 'مرد'), ('F', 'زن')], max_length=1, verbose_name='جنسیت')),
                ('phone_number', models.IntegerField(max_length=12, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(12)], verbose_name='شماره تلفن')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='اسم کالا')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت کالا')),
                ('product_type', models.CharField(choices=[('WRITING', 'ابزار نوشتن'), ('PAPER', 'محصولات کاغذی'), ('ACCESSORY', 'لوازم جانبی'), ('STORAGE', 'وسایل نگهداری'), ('OTHER', 'سایر')], max_length=20, verbose_name='نوع کالا')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='عکس کالا')),
            ],
        ),
        migrations.CreateModel(
            name='WholesalePurchase',
            fields=[
                ('wp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ خرید')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='مجموع خرید')),
            ],
        ),
        migrations.CreateModel(
            name='Wholesaler',
            fields=[
                ('wholesaler_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='نام عمده\u200cفروش')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('address', models.CharField(max_length=255, verbose_name='آدرس')),
            ],
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('debt_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ بدهی')),
                ('due_date', models.DateField(verbose_name='تاریخ سررسید')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده؟')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات بدهی')),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='System.creditor', verbose_name='طلبکار')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='System.person')),
                ('position', models.CharField(default='employees', editable=False, max_length=50, verbose_name='سمت شخص')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/', verbose_name='عکس کارمند')),
                ('job', models.CharField(choices=[('SELLER', 'فروشنده'), ('STOCK', 'انباردار')], max_length=20, verbose_name='سمت')),
            ],
            bases=('System.person',),
        ),
        migrations.CreateModel(
            name='SpecialCustomer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='System.person')),
                ('address', models.CharField(max_length=255, verbose_name='آدرس')),
                ('position', models.CharField(default='specialcustomer', editable=False, max_length=50, verbose_name='سمت شخص')),
            ],
            bases=('System.person',),
        ),
        migrations.CreateModel(
            name='StoreManager',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='System.person')),
                ('position', models.CharField(default='storemanager', editable=False, max_length=50, verbose_name='سمت شخص')),
            ],
            bases=('System.person',),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد موجودی')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System.product', verbose_name='کالا')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('pi_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت واحد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System.product', verbose_name='کالا')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='System.customerpurchase', verbose_name='خرید')),
            ],
        ),
        migrations.AddField(
            model_name='customerpurchase',
            name='products',
            field=models.ManyToManyField(through='System.PurchaseItem', to='System.product', verbose_name='کالاهای خریداری\u200cشده'),
        ),
        migrations.CreateModel(
            name='WholesalePurchaseItem',
            fields=[
                ('wpi_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت واحد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System.product', verbose_name='کالا')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='System.wholesalepurchase', verbose_name='خرید عمده')),
            ],
        ),
        migrations.AddField(
            model_name='wholesalepurchase',
            name='products',
            field=models.ManyToManyField(through='System.WholesalePurchaseItem', to='System.product', verbose_name='کالاهای خریداری\u200cشده'),
        ),
        migrations.AddField(
            model_name='wholesalepurchase',
            name='wholesaler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='System.wholesaler', verbose_name='عمده\u200cفروش'),
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.CharField(choices=[('storemanager', 'مدیر فروشگاه'), ('employees', 'کارمند')], default='employees', editable=False, max_length=50, verbose_name='سمت شخص')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(limit_choices_to={'position': 'employees'}, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر کارمند')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='System.employee', verbose_name='کارمند')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='ساعت ورود')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='ساعت خروج')),
                ('status', models.CharField(choices=[('PRESENT', 'حاضر'), ('ABSENT', 'غایب'), ('LATE', 'دیرکرد')], max_length=10, verbose_name='وضعیت')),
                ('approved_by_manager', models.BooleanField(default=False, verbose_name='تأیید مدیریت')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='System.employee', verbose_name='کارمند')),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('credit_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_debt', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مجموع بدهی')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده؟')),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='System.customerpurchase', verbose_name='خرید مرتبط')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='System.specialcustomer', verbose_name='مشتری ویژه')),
            ],
        ),
        migrations.CreateModel(
            name='StoreManagerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره دفتر')),
                ('responsibilities', models.TextField(blank=True, null=True, verbose_name='مسئولیت\u200cها')),
                ('user', models.OneToOneField(limit_choices_to={'position': 'storemanager'}, on_delete=django.db.models.deletion.CASCADE, related_name='store_manager_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر مدیر فروشگاه')),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='System.storemanager', verbose_name='مدیر فروشگاه')),
            ],
        ),
    ]
