# Generated by Django 5.2.8 on 2026-01-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='creditor/', verbose_name='عکس'),
        ),
    ]
