# Generated by Django 5.2.8 on 2026-01-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0002_creditor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(choices=[('storemanager', 'مدیر فروشگاه'), ('employees', 'کارمند')], default='employees', max_length=50, verbose_name='سمت شخص'),
        ),
    ]
