# Generated by Django 5.2.8 on 2026-02-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0004_alter_person_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.IntegerField(verbose_name='شماره تلفن'),
        ),
    ]
